name: CI (Build & Test)

on:
  pull_request:
    branches: [ main, dev, uat, prod ]
  push:
    branches: [ main, dev, uat, prod ]
    tags: [ 'v*' ]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Maven go-offline
        run: mvn -B -ntp -q dependency:go-offline

      # PRs: full build + tests
      - name: Build & Test (PRs)
        if: ${{ github.event_name == 'pull_request' }}
        run: mvn -B -ntp clean verify

      # Pushes/Tags: fast package (skip tests)
      - name: Package (pushes & tags)
        if: ${{ github.event_name != 'pull_request' }}
        run: mvn -B -ntp clean package -DskipTests

      # Upload all module jars on pushes/tags
      - name: Upload artifacts
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: jars-${{ github.ref_name }}-${{ github.sha }}
          path: |
            balance-service/target/*.jar
            ledger-service/target/*.jar
            plaid-service/target/*.jar
            eureka-server/target/*.jar
          if-no-files-found: error
          retention-days: 14
