name: CI (Build & Test)

on:
  pull_request:
    branches: [ main, dev, uat, prod ]
  push:
    branches: [ main, dev, uat, prod ]
    tags: [ 'v*' ]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module: [ balance-service, ledger-service, plaid-service, eureka-server ]
        include:
          - module: balance-service
          - module: ledger-service
          - module: plaid-service
          - module: eureka-server

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      # Pre-fetch deps for the specific module (run in that dir!)
      - name: Maven go-offline
        working-directory: ${{ matrix.module }}
        run: mvn -B -ntp -q dependency:go-offline

      # PRs: run tests
      - name: Build & Test (PRs)
        if: ${{ github.event_name == 'pull_request' }}
        working-directory: ${{ matrix.module }}
        run: mvn -B -ntp clean verify

      # Pushes/tags: package fast (skip tests)
      - name: Package (pushes & tags)
        if: ${{ github.event_name != 'pull_request' }}
        working-directory: ${{ matrix.module }}
        run: mvn -B -ntp clean package -DskipTests

      # Upload jars for pushes/tags
      - name: Upload artifact (jar)
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.module }}-jar
          path: ${{ matrix.module }}/target/*.jar
          if-no-files-found: error
          retention-days: 14
