name: CI (Build & Test)

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build & Test (${{ matrix.service }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: [balance-service, ledger-service, plaid-service]

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build (skip tests for speed)
        working-directory: ${{ matrix.service }}
        run: mvn -B -ntp clean package -DskipTests
