name: CI (Build & Test)

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, dev, uat, prod ]
    tags: [ 'v*' ]

jobs:
  build:
    name: Build & Test (${{ matrix.service }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: [balance-service, ledger-service, plaid-service]

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      # PRs to main: run tests
      - name: Build & Test (PRs)
        if: ${{ github.event_name == 'pull_request' }}
        working-directory: ${{ matrix.service }}
        run: mvn -B -ntp clean verify

      # Pushes/tags: fast build (skip tests)
      - name: Package (pushes & tags)
        if: ${{ github.event_name != 'pull_request' }}
        working-directory: ${{ matrix.service }}
        run: mvn -B -ntp clean package -DskipTests

      # Upload jars for pushes/tags so envs can deploy them
      - name: Upload artifact (jar)
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.service }}-jar
          path: ${{ matrix.service }}/target/*.jar
          if-no-files-found: error
          retention-days: 14
